# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thermal < Formula
  desc "Terminal contribution heatmap and leaderboard for AI coding assistants"
  homepage "https://thermal.jadmadi.net"
  version "0.13.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_darwin_amd64.tar.gz"
      sha256 "49cc701c85c8af139e7f440a8817b4a2c8466af2d467e3d10868d9a3f335459f"

      def install
        bin.install "thermal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_darwin_arm64.tar.gz"
      sha256 "a77cd0eb9fd55aa3892ed6a7f1b0feb546360d772a5779c5502239d706323f8c"

      def install
        bin.install "thermal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_linux_amd64.tar.gz"
      sha256 "4554e6a57478506c6b6530e416df9b3ed9a4c02fa81895d5bfa8106f6109d44b"

      def install
        bin.install "thermal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_linux_arm64.tar.gz"
      sha256 "6ffa002e6a1bd768a4bd1ec4eb2fefe69ebc7deb14fa377d7af14edc8a886bce"

      def install
        bin.install "thermal"
      end
    end
  end

  test do
    system "#{bin}/thermal", "version"
  end
end
