# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thermal < Formula
  desc "Terminal contribution heatmap and leaderboard for AI coding assistants"
  homepage "https://thermal.jadmadi.net"
  version "0.13.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_darwin_amd64.tar.gz"
      sha256 "20315953392e747cf328cf175313befbb04ad257fd15a6f1cb58e81ef949a9e0"

      def install
        bin.install "thermal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_darwin_arm64.tar.gz"
      sha256 "cd14292d709eb5ed20afc23d141671657643deec224a519f21ccb7060a948e1a"

      def install
        bin.install "thermal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_linux_amd64.tar.gz"
      sha256 "4272f089142bc1a7743160c0c146416e272658f83fbe36571532b43304291fce"

      def install
        bin.install "thermal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jadmadi/thermal/releases/download/v0.13.0/thermal_0.13.0_linux_arm64.tar.gz"
      sha256 "ae1e747afde8c9918811cecf1285c8ff9e93f05ba39cfbe932344a179093ad1d"

      def install
        bin.install "thermal"
      end
    end
  end

  test do
    system "#{bin}/thermal", "version"
  end
end
